version: '3'

services:

  ### PHP-FPM Container #######################################
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ${WEB_ROOT}:/var/www/html
    expose:
      - "9000"
    restart: always
    stdin_open: true
    tty: true

  nginx:
    build:
      context: ./nginx
    volumes:
      - ${WEB_ROOT}:/var/www/html
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    restart: always
    
volumes:
  mysql_data:
networks:
  default:
    external:
      name: ${USER_NETWORK}